name: helloworld
tag: <autotag>
namespace: dev
azureAccount: staging

cpu: 0.2
memory: 256M

initialDelaySeconds: 120

env:
  APP_NAME: 'helloworld-dev'
  PY_ENV: 'development'

lb:
  type: nginx-internal
  hosts:
    - host: helloworld.dev.iaclab.com
      paths: ["/"]